### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by happybang** [keymetrics/pm2-io-apm#234]
How much impact does pm2-io-apm have on server performance can we ignore ?

**Comment by vmarchaud** [comment]
Hey,

It depend which features you are using, the feature that have the most impact in term of performance is the tracing and it's not enabled by default. It can have between 5 and 20% of overhead, it depend which nodejs version you are using (the newest is better of course) and how your applications is developed (using the tracing with async/await is slower than Promise or callback)
The CPU/Memory profiler are running in parallel so the only impact is receiving the command and sending back the file.
Other feature have pretty much no cost since they only send simple data to our servers.
